server:
  port: 8082
spring:
  application:
    name: guli-order
  datasource:
    url: jdbc:mysql://localhost:3306/guli_order?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: abc123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  sleuth:
    sampler:
      # 采样率：所有请求数据都被采样提交到zipkin
      probability: 1.0

eureka:
  instance:
    ip-address: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
# ribbon发起远程访问时 默认等待超时时长为1s，如果超过1s报错
# springboot2.0以后 不推荐使用ribbon：  ribbon代码耦合度高
# 2.0以后  feign对ribbon作了封装，但是ribbon没有整合spring 没有提供注解快速在springboot项目中使用
# springboot最后对feign作了封装  叫做openfeign  并提供了注解简化了feign的使用
ribbon:  # 一定会配置超时时长
  # 当前服务ribbon远程和要访问的服务建立网络连接的超时时间
  ConnectTimeout: 5000
  # 连接建立成功 目标服务业务执行时间的超时时间
  ReadTimeout: 5000
logging:
  level:
    # 全局日志级别为debug
    root: info
    com.atguigu.guli.order.feign: debug
# 以web的方式暴露当前项目的数据流
management:
  endpoints:
    web:
      exposure:
        include: '*'
hystrix:
  dashboard:
    # 允许监控当前项目数据流的服务器
    proxy-stream-allow-list: 'localhost'