server:
  port: 8082
spring:
  application:
    name: guli-order
  datasource:
    url: jdbc:mysql://localhost:3306/guli_order?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123
  jpa:
    show-sql: true
eureka:
  instance:
    ip-address: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
